package com.embark.entity;

// Generated 18 Jul, 2016 5:56:24 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DealerGroupMaster generated by hbm2java
 */
@Entity
@Table(name = "dealer_group_master", catalog = "salex")
public class DealerGroupMaster implements java.io.Serializable {

	private int dealerGroupId;
	private OrganizationMaster organizationMaster;
	private DivisionMaster divisionMaster;
	private DealerGroupMaster dealerGroupMaster;
	private String dealerGroupDescription;
	private int hierarchyLevel;
	private Integer ownerId;
	private Boolean isInternal;
	private Integer createdBy;
	private Date createdDate;
	private Integer lastModifiedBy;
	private Date lastModifiedDate;
	private String attribute1;
	private String attribute2;
	private String attribute3;
	private Set<DealerGroupMaster> dealerGroupMasters = new HashSet<DealerGroupMaster>(
			0);
	private Set<DealerItemMaster> dealerItemMasters = new HashSet<DealerItemMaster>(
			0);

	public DealerGroupMaster() {
	}

	public DealerGroupMaster(int dealerGroupId,
			OrganizationMaster organizationMaster,
			DivisionMaster divisionMaster, String dealerGroupDescription,
			int hierarchyLevel) {
		this.dealerGroupId = dealerGroupId;
		this.organizationMaster = organizationMaster;
		this.divisionMaster = divisionMaster;
		this.dealerGroupDescription = dealerGroupDescription;
		this.hierarchyLevel = hierarchyLevel;
	}

	public DealerGroupMaster(int dealerGroupId,
			OrganizationMaster organizationMaster,
			DivisionMaster divisionMaster, DealerGroupMaster dealerGroupMaster,
			String dealerGroupDescription, int hierarchyLevel, Integer ownerId,
			Boolean isInternal, Integer createdBy, Date createdDate,
			Integer lastModifiedBy, Date lastModifiedDate, String attribute1,
			String attribute2, String attribute3,
			Set<DealerGroupMaster> dealerGroupMasters,
			Set<DealerItemMaster> dealerItemMasters) {
		this.dealerGroupId = dealerGroupId;
		this.organizationMaster = organizationMaster;
		this.divisionMaster = divisionMaster;
		this.dealerGroupMaster = dealerGroupMaster;
		this.dealerGroupDescription = dealerGroupDescription;
		this.hierarchyLevel = hierarchyLevel;
		this.ownerId = ownerId;
		this.isInternal = isInternal;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifiedDate = lastModifiedDate;
		this.attribute1 = attribute1;
		this.attribute2 = attribute2;
		this.attribute3 = attribute3;
		this.dealerGroupMasters = dealerGroupMasters;
		this.dealerItemMasters = dealerItemMasters;
	}

	@Id
	@Column(name = "Dealer_Group_Id", unique = true, nullable = false)
	public int getDealerGroupId() {
		return this.dealerGroupId;
	}

	public void setDealerGroupId(int dealerGroupId) {
		this.dealerGroupId = dealerGroupId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Org_Id", nullable = false)
	public OrganizationMaster getOrganizationMaster() {
		return this.organizationMaster;
	}

	public void setOrganizationMaster(OrganizationMaster organizationMaster) {
		this.organizationMaster = organizationMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Div_Id", nullable = false)
	public DivisionMaster getDivisionMaster() {
		return this.divisionMaster;
	}

	public void setDivisionMaster(DivisionMaster divisionMaster) {
		this.divisionMaster = divisionMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Dealer_Parent_Group_Id")
	public DealerGroupMaster getDealerGroupMaster() {
		return this.dealerGroupMaster;
	}

	public void setDealerGroupMaster(DealerGroupMaster dealerGroupMaster) {
		this.dealerGroupMaster = dealerGroupMaster;
	}

	@Column(name = "Dealer_Group_Description", nullable = false, length = 100)
	public String getDealerGroupDescription() {
		return this.dealerGroupDescription;
	}

	public void setDealerGroupDescription(String dealerGroupDescription) {
		this.dealerGroupDescription = dealerGroupDescription;
	}

	@Column(name = "Hierarchy_Level", nullable = false)
	public int getHierarchyLevel() {
		return this.hierarchyLevel;
	}

	public void setHierarchyLevel(int hierarchyLevel) {
		this.hierarchyLevel = hierarchyLevel;
	}

	@Column(name = "Owner_Id")
	public Integer getOwnerId() {
		return this.ownerId;
	}

	public void setOwnerId(Integer ownerId) {
		this.ownerId = ownerId;
	}

	@Column(name = "Is_Internal")
	public Boolean getIsInternal() {
		return this.isInternal;
	}

	public void setIsInternal(Boolean isInternal) {
		this.isInternal = isInternal;
	}

	@Column(name = "Created_By")
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Created_Date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "Last_Modified_By")
	public Integer getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(Integer lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Last_Modified_Date", length = 19)
	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	@Column(name = "Attribute_1", length = 20)
	public String getAttribute1() {
		return this.attribute1;
	}

	public void setAttribute1(String attribute1) {
		this.attribute1 = attribute1;
	}

	@Column(name = "Attribute_2", length = 20)
	public String getAttribute2() {
		return this.attribute2;
	}

	public void setAttribute2(String attribute2) {
		this.attribute2 = attribute2;
	}

	@Column(name = "Attribute_3", length = 20)
	public String getAttribute3() {
		return this.attribute3;
	}

	public void setAttribute3(String attribute3) {
		this.attribute3 = attribute3;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dealerGroupMaster")
	public Set<DealerGroupMaster> getDealerGroupMasters() {
		return this.dealerGroupMasters;
	}

	public void setDealerGroupMasters(Set<DealerGroupMaster> dealerGroupMasters) {
		this.dealerGroupMasters = dealerGroupMasters;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dealerGroupMaster")
	public Set<DealerItemMaster> getDealerItemMasters() {
		return this.dealerItemMasters;
	}

	public void setDealerItemMasters(Set<DealerItemMaster> dealerItemMasters) {
		this.dealerItemMasters = dealerItemMasters;
	}

}
