package com.embark.entity;

// Generated 18 Jul, 2016 5:56:24 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GroupMaster generated by hbm2java
 */
@Entity
@Table(name = "group_master", catalog = "salex")
public class GroupMaster implements java.io.Serializable {

	private int groupId;
	private OrganizationMaster organizationMaster;
	private DivisionMaster divisionMaster;
	private GroupMaster groupMaster;
	private String groupDescription;
	private int hierarchyLevel;
	private Integer ownerId;
	private Boolean isInternal;
	private Integer createdBy;
	private Date createdDate;
	private Integer lastModifiedBy;
	private Date lastModifiedDate;
	private String attribute1;
	private String attribute2;
	private String attribute3;
	private Set<ItemMaster> itemMasters = new HashSet<ItemMaster>(0);
	private Set<GroupMaster> groupMasters = new HashSet<GroupMaster>(0);

	public GroupMaster() {
	}

	public GroupMaster(int groupId, OrganizationMaster organizationMaster,
			DivisionMaster divisionMaster, String groupDescription,
			int hierarchyLevel) {
		this.groupId = groupId;
		this.organizationMaster = organizationMaster;
		this.divisionMaster = divisionMaster;
		this.groupDescription = groupDescription;
		this.hierarchyLevel = hierarchyLevel;
	}

	public GroupMaster(int groupId, OrganizationMaster organizationMaster,
			DivisionMaster divisionMaster, GroupMaster groupMaster,
			String groupDescription, int hierarchyLevel, Integer ownerId,
			Boolean isInternal, Integer createdBy, Date createdDate,
			Integer lastModifiedBy, Date lastModifiedDate, String attribute1,
			String attribute2, String attribute3, Set<ItemMaster> itemMasters,
			Set<GroupMaster> groupMasters) {
		this.groupId = groupId;
		this.organizationMaster = organizationMaster;
		this.divisionMaster = divisionMaster;
		this.groupMaster = groupMaster;
		this.groupDescription = groupDescription;
		this.hierarchyLevel = hierarchyLevel;
		this.ownerId = ownerId;
		this.isInternal = isInternal;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifiedDate = lastModifiedDate;
		this.attribute1 = attribute1;
		this.attribute2 = attribute2;
		this.attribute3 = attribute3;
		this.itemMasters = itemMasters;
		this.groupMasters = groupMasters;
	}

	@Id
	@Column(name = "Group_Id", unique = true, nullable = false)
	public int getGroupId() {
		return this.groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Org_Id", nullable = false)
	public OrganizationMaster getOrganizationMaster() {
		return this.organizationMaster;
	}

	public void setOrganizationMaster(OrganizationMaster organizationMaster) {
		this.organizationMaster = organizationMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Div_Id", nullable = false)
	public DivisionMaster getDivisionMaster() {
		return this.divisionMaster;
	}

	public void setDivisionMaster(DivisionMaster divisionMaster) {
		this.divisionMaster = divisionMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Parent_Group_Id")
	public GroupMaster getGroupMaster() {
		return this.groupMaster;
	}

	public void setGroupMaster(GroupMaster groupMaster) {
		this.groupMaster = groupMaster;
	}

	@Column(name = "Group_Description", nullable = false, length = 100)
	public String getGroupDescription() {
		return this.groupDescription;
	}

	public void setGroupDescription(String groupDescription) {
		this.groupDescription = groupDescription;
	}

	@Column(name = "Hierarchy_Level", nullable = false)
	public int getHierarchyLevel() {
		return this.hierarchyLevel;
	}

	public void setHierarchyLevel(int hierarchyLevel) {
		this.hierarchyLevel = hierarchyLevel;
	}

	@Column(name = "Owner_Id")
	public Integer getOwnerId() {
		return this.ownerId;
	}

	public void setOwnerId(Integer ownerId) {
		this.ownerId = ownerId;
	}

	@Column(name = "Is_Internal")
	public Boolean getIsInternal() {
		return this.isInternal;
	}

	public void setIsInternal(Boolean isInternal) {
		this.isInternal = isInternal;
	}

	@Column(name = "Created_By")
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Created_Date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "Last_Modified_By")
	public Integer getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(Integer lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Last_Modified_Date", length = 19)
	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	@Column(name = "Attribute_1", length = 20)
	public String getAttribute1() {
		return this.attribute1;
	}

	public void setAttribute1(String attribute1) {
		this.attribute1 = attribute1;
	}

	@Column(name = "Attribute_2", length = 20)
	public String getAttribute2() {
		return this.attribute2;
	}

	public void setAttribute2(String attribute2) {
		this.attribute2 = attribute2;
	}

	@Column(name = "Attribute_3", length = 20)
	public String getAttribute3() {
		return this.attribute3;
	}

	public void setAttribute3(String attribute3) {
		this.attribute3 = attribute3;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "groupMaster")
	public Set<ItemMaster> getItemMasters() {
		return this.itemMasters;
	}

	public void setItemMasters(Set<ItemMaster> itemMasters) {
		this.itemMasters = itemMasters;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "groupMaster")
	public Set<GroupMaster> getGroupMasters() {
		return this.groupMasters;
	}

	public void setGroupMasters(Set<GroupMaster> groupMasters) {
		this.groupMasters = groupMasters;
	}

}
