package com.embark.entity;

// Generated 18 Jul, 2016 5:56:24 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LocationMaster generated by hbm2java
 */
@Entity
@Table(name = "location_master", catalog = "salex")
public class LocationMaster implements java.io.Serializable {

	private int locationId;
	private OrganizationMaster organizationMaster;
	private DivisionMaster divisionMaster;
	private String locationCode;
	private String locationName;
	private String phone;
	private String email;
	private String addressLine1;
	private String addressLine2;
	private String addressLine3;
	private int pin;
	private String city;
	private String state;
	private String country;
	private Integer contactPerson;
	private boolean isActive;
	private Boolean isPrimary;
	private String notes;
	private Integer ownerId;
	private Boolean isInternal;
	private Integer createdBy;
	private Date createdDate;
	private Integer lastModifiedBy;
	private Date lastModifiedDate;
	private String attribute1;
	private String attribute2;
	private String attribute3;
	private Set<UserMap> userMaps = new HashSet<UserMap>(0);
	private Set<Invoice> invoices = new HashSet<Invoice>(0);

	public LocationMaster() {
	}

	public LocationMaster(int locationId,
			OrganizationMaster organizationMaster,
			DivisionMaster divisionMaster, int pin, String city, String state,
			String country, boolean isActive) {
		this.locationId = locationId;
		this.organizationMaster = organizationMaster;
		this.divisionMaster = divisionMaster;
		this.pin = pin;
		this.city = city;
		this.state = state;
		this.country = country;
		this.isActive = isActive;
	}

	public LocationMaster(int locationId,
			OrganizationMaster organizationMaster,
			DivisionMaster divisionMaster, String locationCode,
			String locationName, String phone, String email,
			String addressLine1, String addressLine2, String addressLine3,
			int pin, String city, String state, String country,
			Integer contactPerson, boolean isActive, Boolean isPrimary,
			String notes, Integer ownerId, Boolean isInternal,
			Integer createdBy, Date createdDate, Integer lastModifiedBy,
			Date lastModifiedDate, String attribute1, String attribute2,
			String attribute3, Set<UserMap> userMaps, Set<Invoice> invoices) {
		this.locationId = locationId;
		this.organizationMaster = organizationMaster;
		this.divisionMaster = divisionMaster;
		this.locationCode = locationCode;
		this.locationName = locationName;
		this.phone = phone;
		this.email = email;
		this.addressLine1 = addressLine1;
		this.addressLine2 = addressLine2;
		this.addressLine3 = addressLine3;
		this.pin = pin;
		this.city = city;
		this.state = state;
		this.country = country;
		this.contactPerson = contactPerson;
		this.isActive = isActive;
		this.isPrimary = isPrimary;
		this.notes = notes;
		this.ownerId = ownerId;
		this.isInternal = isInternal;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifiedDate = lastModifiedDate;
		this.attribute1 = attribute1;
		this.attribute2 = attribute2;
		this.attribute3 = attribute3;
		this.userMaps = userMaps;
		this.invoices = invoices;
	}

	@Id
	@Column(name = "Location_Id", unique = true, nullable = false)
	public int getLocationId() {
		return this.locationId;
	}

	public void setLocationId(int locationId) {
		this.locationId = locationId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Org_Id", nullable = false)
	public OrganizationMaster getOrganizationMaster() {
		return this.organizationMaster;
	}

	public void setOrganizationMaster(OrganizationMaster organizationMaster) {
		this.organizationMaster = organizationMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Div_Id", nullable = false)
	public DivisionMaster getDivisionMaster() {
		return this.divisionMaster;
	}

	public void setDivisionMaster(DivisionMaster divisionMaster) {
		this.divisionMaster = divisionMaster;
	}

	@Column(name = "Location_Code", length = 20)
	public String getLocationCode() {
		return this.locationCode;
	}

	public void setLocationCode(String locationCode) {
		this.locationCode = locationCode;
	}

	@Column(name = "Location_Name", length = 20)
	public String getLocationName() {
		return this.locationName;
	}

	public void setLocationName(String locationName) {
		this.locationName = locationName;
	}

	@Column(name = "Phone", length = 20)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "Email", length = 20)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "Address_Line_1", length = 20)
	public String getAddressLine1() {
		return this.addressLine1;
	}

	public void setAddressLine1(String addressLine1) {
		this.addressLine1 = addressLine1;
	}

	@Column(name = "Address_Line_2", length = 20)
	public String getAddressLine2() {
		return this.addressLine2;
	}

	public void setAddressLine2(String addressLine2) {
		this.addressLine2 = addressLine2;
	}

	@Column(name = "Address_Line_3", length = 20)
	public String getAddressLine3() {
		return this.addressLine3;
	}

	public void setAddressLine3(String addressLine3) {
		this.addressLine3 = addressLine3;
	}

	@Column(name = "Pin", nullable = false)
	public int getPin() {
		return this.pin;
	}

	public void setPin(int pin) {
		this.pin = pin;
	}

	@Column(name = "City", nullable = false, length = 20)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "State", nullable = false, length = 20)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "Country", nullable = false, length = 20)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "Contact_Person")
	public Integer getContactPerson() {
		return this.contactPerson;
	}

	public void setContactPerson(Integer contactPerson) {
		this.contactPerson = contactPerson;
	}

	@Column(name = "Is_Active", nullable = false)
	public boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}

	@Column(name = "Is_Primary")
	public Boolean getIsPrimary() {
		return this.isPrimary;
	}

	public void setIsPrimary(Boolean isPrimary) {
		this.isPrimary = isPrimary;
	}

	@Column(name = "Notes", length = 20)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Column(name = "Owner_Id")
	public Integer getOwnerId() {
		return this.ownerId;
	}

	public void setOwnerId(Integer ownerId) {
		this.ownerId = ownerId;
	}

	@Column(name = "Is_Internal")
	public Boolean getIsInternal() {
		return this.isInternal;
	}

	public void setIsInternal(Boolean isInternal) {
		this.isInternal = isInternal;
	}

	@Column(name = "Created_By")
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Created_Date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "Last_Modified_By")
	public Integer getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(Integer lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Last_Modified_Date", length = 19)
	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	@Column(name = "Attribute_1", length = 20)
	public String getAttribute1() {
		return this.attribute1;
	}

	public void setAttribute1(String attribute1) {
		this.attribute1 = attribute1;
	}

	@Column(name = "Attribute_2", length = 20)
	public String getAttribute2() {
		return this.attribute2;
	}

	public void setAttribute2(String attribute2) {
		this.attribute2 = attribute2;
	}

	@Column(name = "Attribute_3", length = 20)
	public String getAttribute3() {
		return this.attribute3;
	}

	public void setAttribute3(String attribute3) {
		this.attribute3 = attribute3;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "locationMaster")
	public Set<UserMap> getUserMaps() {
		return this.userMaps;
	}

	public void setUserMaps(Set<UserMap> userMaps) {
		this.userMaps = userMaps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "locationMaster")
	public Set<Invoice> getInvoices() {
		return this.invoices;
	}

	public void setInvoices(Set<Invoice> invoices) {
		this.invoices = invoices;
	}

}
