package com.embark.entity;

// Generated 18 Jul, 2016 5:56:24 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PasswordPolicy generated by hbm2java
 */
@Entity
@Table(name = "password_policy", catalog = "salex")
public class PasswordPolicy implements java.io.Serializable {

	private int policyId;
	private OrganizationMaster organizationMaster;
	private DivisionMaster divisionMaster;
	private String policyCode;
	private String policyName;
	private Integer minLength;
	private Integer maxLength;
	private Boolean isSpecialChar;
	private Boolean isAplhanumeric;
	private Integer validityDays;
	private Integer notificationDays;
	private Boolean isActive;
	private Integer ownerId;
	private Boolean isInternal;
	private Integer createdBy;
	private Date createdDate;
	private Integer lastModifiedBy;
	private Date lastModifiedDate;
	private String attribute1;
	private String attribute2;
	private String attribute3;
	private Set<PasswordSecurity> passwordSecurities = new HashSet<PasswordSecurity>(
			0);

	public PasswordPolicy() {
	}

	public PasswordPolicy(int policyId, OrganizationMaster organizationMaster,
			DivisionMaster divisionMaster, String policyCode) {
		this.policyId = policyId;
		this.organizationMaster = organizationMaster;
		this.divisionMaster = divisionMaster;
		this.policyCode = policyCode;
	}

	public PasswordPolicy(int policyId, OrganizationMaster organizationMaster,
			DivisionMaster divisionMaster, String policyCode,
			String policyName, Integer minLength, Integer maxLength,
			Boolean isSpecialChar, Boolean isAplhanumeric,
			Integer validityDays, Integer notificationDays, Boolean isActive,
			Integer ownerId, Boolean isInternal, Integer createdBy,
			Date createdDate, Integer lastModifiedBy, Date lastModifiedDate,
			String attribute1, String attribute2, String attribute3,
			Set<PasswordSecurity> passwordSecurities) {
		this.policyId = policyId;
		this.organizationMaster = organizationMaster;
		this.divisionMaster = divisionMaster;
		this.policyCode = policyCode;
		this.policyName = policyName;
		this.minLength = minLength;
		this.maxLength = maxLength;
		this.isSpecialChar = isSpecialChar;
		this.isAplhanumeric = isAplhanumeric;
		this.validityDays = validityDays;
		this.notificationDays = notificationDays;
		this.isActive = isActive;
		this.ownerId = ownerId;
		this.isInternal = isInternal;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifiedDate = lastModifiedDate;
		this.attribute1 = attribute1;
		this.attribute2 = attribute2;
		this.attribute3 = attribute3;
		this.passwordSecurities = passwordSecurities;
	}

	@Id
	@Column(name = "Policy_Id", unique = true, nullable = false)
	public int getPolicyId() {
		return this.policyId;
	}

	public void setPolicyId(int policyId) {
		this.policyId = policyId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Org_Id", nullable = false)
	public OrganizationMaster getOrganizationMaster() {
		return this.organizationMaster;
	}

	public void setOrganizationMaster(OrganizationMaster organizationMaster) {
		this.organizationMaster = organizationMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Div_Id", nullable = false)
	public DivisionMaster getDivisionMaster() {
		return this.divisionMaster;
	}

	public void setDivisionMaster(DivisionMaster divisionMaster) {
		this.divisionMaster = divisionMaster;
	}

	@Column(name = "Policy_Code", nullable = false, length = 20)
	public String getPolicyCode() {
		return this.policyCode;
	}

	public void setPolicyCode(String policyCode) {
		this.policyCode = policyCode;
	}

	@Column(name = "Policy_Name", length = 20)
	public String getPolicyName() {
		return this.policyName;
	}

	public void setPolicyName(String policyName) {
		this.policyName = policyName;
	}

	@Column(name = "Min_Length")
	public Integer getMinLength() {
		return this.minLength;
	}

	public void setMinLength(Integer minLength) {
		this.minLength = minLength;
	}

	@Column(name = "Max_Length")
	public Integer getMaxLength() {
		return this.maxLength;
	}

	public void setMaxLength(Integer maxLength) {
		this.maxLength = maxLength;
	}

	@Column(name = "Is_Special_Char")
	public Boolean getIsSpecialChar() {
		return this.isSpecialChar;
	}

	public void setIsSpecialChar(Boolean isSpecialChar) {
		this.isSpecialChar = isSpecialChar;
	}

	@Column(name = "Is_Aplhanumeric")
	public Boolean getIsAplhanumeric() {
		return this.isAplhanumeric;
	}

	public void setIsAplhanumeric(Boolean isAplhanumeric) {
		this.isAplhanumeric = isAplhanumeric;
	}

	@Column(name = "Validity_Days")
	public Integer getValidityDays() {
		return this.validityDays;
	}

	public void setValidityDays(Integer validityDays) {
		this.validityDays = validityDays;
	}

	@Column(name = "Notification_Days")
	public Integer getNotificationDays() {
		return this.notificationDays;
	}

	public void setNotificationDays(Integer notificationDays) {
		this.notificationDays = notificationDays;
	}

	@Column(name = "Is_Active")
	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	@Column(name = "Owner_Id")
	public Integer getOwnerId() {
		return this.ownerId;
	}

	public void setOwnerId(Integer ownerId) {
		this.ownerId = ownerId;
	}

	@Column(name = "Is_Internal")
	public Boolean getIsInternal() {
		return this.isInternal;
	}

	public void setIsInternal(Boolean isInternal) {
		this.isInternal = isInternal;
	}

	@Column(name = "Created_By")
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Created_Date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "Last_Modified_By")
	public Integer getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(Integer lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Last_Modified_Date", length = 19)
	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	@Column(name = "Attribute_1", length = 20)
	public String getAttribute1() {
		return this.attribute1;
	}

	public void setAttribute1(String attribute1) {
		this.attribute1 = attribute1;
	}

	@Column(name = "Attribute_2", length = 20)
	public String getAttribute2() {
		return this.attribute2;
	}

	public void setAttribute2(String attribute2) {
		this.attribute2 = attribute2;
	}

	@Column(name = "Attribute_3", length = 20)
	public String getAttribute3() {
		return this.attribute3;
	}

	public void setAttribute3(String attribute3) {
		this.attribute3 = attribute3;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "passwordPolicy")
	public Set<PasswordSecurity> getPasswordSecurities() {
		return this.passwordSecurities;
	}

	public void setPasswordSecurities(Set<PasswordSecurity> passwordSecurities) {
		this.passwordSecurities = passwordSecurities;
	}

}
