package com.embark.entity;

// Generated 18 Jul, 2016 5:56:24 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PasswordSecurity generated by hbm2java
 */
@Entity
@Table(name = "password_security", catalog = "salex")
public class PasswordSecurity implements java.io.Serializable {

	private int securityId;
	private PasswordPolicy passwordPolicy;
	private OrganizationMaster organizationMaster;
	private User user;
	private DivisionMaster divisionMaster;
	private SecurityQuestions securityQuestions;
	private String recoveryAnswer;
	private Date lastRestDate;
	private Date expiryDate;
	private Boolean isExpired;
	private Integer ownerId;
	private Boolean isInternal;
	private Integer createdBy;
	private Date createdDate;
	private Integer lastModifiedBy;
	private Date lastModifiedDate;
	private String attribute1;
	private String attribute2;
	private String attribute3;

	public PasswordSecurity() {
	}

	public PasswordSecurity(int securityId, PasswordPolicy passwordPolicy,
			OrganizationMaster organizationMaster, User user,
			DivisionMaster divisionMaster) {
		this.securityId = securityId;
		this.passwordPolicy = passwordPolicy;
		this.organizationMaster = organizationMaster;
		this.user = user;
		this.divisionMaster = divisionMaster;
	}

	public PasswordSecurity(int securityId, PasswordPolicy passwordPolicy,
			OrganizationMaster organizationMaster, User user,
			DivisionMaster divisionMaster, SecurityQuestions securityQuestions,
			String recoveryAnswer, Date lastRestDate, Date expiryDate,
			Boolean isExpired, Integer ownerId, Boolean isInternal,
			Integer createdBy, Date createdDate, Integer lastModifiedBy,
			Date lastModifiedDate, String attribute1, String attribute2,
			String attribute3) {
		this.securityId = securityId;
		this.passwordPolicy = passwordPolicy;
		this.organizationMaster = organizationMaster;
		this.user = user;
		this.divisionMaster = divisionMaster;
		this.securityQuestions = securityQuestions;
		this.recoveryAnswer = recoveryAnswer;
		this.lastRestDate = lastRestDate;
		this.expiryDate = expiryDate;
		this.isExpired = isExpired;
		this.ownerId = ownerId;
		this.isInternal = isInternal;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifiedDate = lastModifiedDate;
		this.attribute1 = attribute1;
		this.attribute2 = attribute2;
		this.attribute3 = attribute3;
	}

	@Id
	@Column(name = "Security_Id", unique = true, nullable = false)
	public int getSecurityId() {
		return this.securityId;
	}

	public void setSecurityId(int securityId) {
		this.securityId = securityId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Policy_Id", nullable = false)
	public PasswordPolicy getPasswordPolicy() {
		return this.passwordPolicy;
	}

	public void setPasswordPolicy(PasswordPolicy passwordPolicy) {
		this.passwordPolicy = passwordPolicy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Org_Id", nullable = false)
	public OrganizationMaster getOrganizationMaster() {
		return this.organizationMaster;
	}

	public void setOrganizationMaster(OrganizationMaster organizationMaster) {
		this.organizationMaster = organizationMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "User_Id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Div_Id", nullable = false)
	public DivisionMaster getDivisionMaster() {
		return this.divisionMaster;
	}

	public void setDivisionMaster(DivisionMaster divisionMaster) {
		this.divisionMaster = divisionMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Secure_Question_Id")
	public SecurityQuestions getSecurityQuestions() {
		return this.securityQuestions;
	}

	public void setSecurityQuestions(SecurityQuestions securityQuestions) {
		this.securityQuestions = securityQuestions;
	}

	@Column(name = "Recovery_Answer", length = 20)
	public String getRecoveryAnswer() {
		return this.recoveryAnswer;
	}

	public void setRecoveryAnswer(String recoveryAnswer) {
		this.recoveryAnswer = recoveryAnswer;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Last_Rest_Date", length = 10)
	public Date getLastRestDate() {
		return this.lastRestDate;
	}

	public void setLastRestDate(Date lastRestDate) {
		this.lastRestDate = lastRestDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Expiry_Date", length = 10)
	public Date getExpiryDate() {
		return this.expiryDate;
	}

	public void setExpiryDate(Date expiryDate) {
		this.expiryDate = expiryDate;
	}

	@Column(name = "Is_Expired")
	public Boolean getIsExpired() {
		return this.isExpired;
	}

	public void setIsExpired(Boolean isExpired) {
		this.isExpired = isExpired;
	}

	@Column(name = "Owner_Id")
	public Integer getOwnerId() {
		return this.ownerId;
	}

	public void setOwnerId(Integer ownerId) {
		this.ownerId = ownerId;
	}

	@Column(name = "Is_Internal")
	public Boolean getIsInternal() {
		return this.isInternal;
	}

	public void setIsInternal(Boolean isInternal) {
		this.isInternal = isInternal;
	}

	@Column(name = "Created_By")
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Created_Date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "Last_Modified_By")
	public Integer getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(Integer lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Last_Modified_Date", length = 19)
	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	@Column(name = "Attribute_1", length = 20)
	public String getAttribute1() {
		return this.attribute1;
	}

	public void setAttribute1(String attribute1) {
		this.attribute1 = attribute1;
	}

	@Column(name = "Attribute_2", length = 20)
	public String getAttribute2() {
		return this.attribute2;
	}

	public void setAttribute2(String attribute2) {
		this.attribute2 = attribute2;
	}

	@Column(name = "Attribute_3", length = 20)
	public String getAttribute3() {
		return this.attribute3;
	}

	public void setAttribute3(String attribute3) {
		this.attribute3 = attribute3;
	}

}
