package com.embark.entity;

// Generated 18 Jul, 2016 5:56:24 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SeriesMaster generated by hbm2java
 */
@Entity
@Table(name = "series_master", catalog = "salex")
public class SeriesMaster implements java.io.Serializable {

	private int seriesAutoId;
	private OrganizationMaster organizationMaster;
	private DivisionMaster divisionMaster;
	private String seriesName;
	private String associatedTable;
	private String associatedField;
	private String prefix;
	private String postfix;
	private Integer incrementBy;
	private Integer counterLength;
	private Integer currentCounter;
	private Integer ownerId;
	private Integer createdBy;
	private Date createdDate;
	private Integer lastModifiedBy;
	private Date lastModifiedDate;
	private String attribute1;
	private String attribute2;
	private String attribute3;

	public SeriesMaster() {
	}

	public SeriesMaster(int seriesAutoId,
			OrganizationMaster organizationMaster, DivisionMaster divisionMaster) {
		this.seriesAutoId = seriesAutoId;
		this.organizationMaster = organizationMaster;
		this.divisionMaster = divisionMaster;
	}

	public SeriesMaster(int seriesAutoId,
			OrganizationMaster organizationMaster,
			DivisionMaster divisionMaster, String seriesName,
			String associatedTable, String associatedField, String prefix,
			String postfix, Integer incrementBy, Integer counterLength,
			Integer currentCounter, Integer ownerId, Integer createdBy,
			Date createdDate, Integer lastModifiedBy, Date lastModifiedDate,
			String attribute1, String attribute2, String attribute3) {
		this.seriesAutoId = seriesAutoId;
		this.organizationMaster = organizationMaster;
		this.divisionMaster = divisionMaster;
		this.seriesName = seriesName;
		this.associatedTable = associatedTable;
		this.associatedField = associatedField;
		this.prefix = prefix;
		this.postfix = postfix;
		this.incrementBy = incrementBy;
		this.counterLength = counterLength;
		this.currentCounter = currentCounter;
		this.ownerId = ownerId;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifiedDate = lastModifiedDate;
		this.attribute1 = attribute1;
		this.attribute2 = attribute2;
		this.attribute3 = attribute3;
	}

	@Id
	@Column(name = "Series_Auto_Id", unique = true, nullable = false)
	public int getSeriesAutoId() {
		return this.seriesAutoId;
	}

	public void setSeriesAutoId(int seriesAutoId) {
		this.seriesAutoId = seriesAutoId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Org_Id", nullable = false)
	public OrganizationMaster getOrganizationMaster() {
		return this.organizationMaster;
	}

	public void setOrganizationMaster(OrganizationMaster organizationMaster) {
		this.organizationMaster = organizationMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Div_Id", nullable = false)
	public DivisionMaster getDivisionMaster() {
		return this.divisionMaster;
	}

	public void setDivisionMaster(DivisionMaster divisionMaster) {
		this.divisionMaster = divisionMaster;
	}

	@Column(name = "Series_Name", length = 20)
	public String getSeriesName() {
		return this.seriesName;
	}

	public void setSeriesName(String seriesName) {
		this.seriesName = seriesName;
	}

	@Column(name = "Associated_Table", length = 20)
	public String getAssociatedTable() {
		return this.associatedTable;
	}

	public void setAssociatedTable(String associatedTable) {
		this.associatedTable = associatedTable;
	}

	@Column(name = "Associated_Field", length = 20)
	public String getAssociatedField() {
		return this.associatedField;
	}

	public void setAssociatedField(String associatedField) {
		this.associatedField = associatedField;
	}

	@Column(name = "Prefix", length = 20)
	public String getPrefix() {
		return this.prefix;
	}

	public void setPrefix(String prefix) {
		this.prefix = prefix;
	}

	@Column(name = "Postfix", length = 20)
	public String getPostfix() {
		return this.postfix;
	}

	public void setPostfix(String postfix) {
		this.postfix = postfix;
	}

	@Column(name = "Increment_By")
	public Integer getIncrementBy() {
		return this.incrementBy;
	}

	public void setIncrementBy(Integer incrementBy) {
		this.incrementBy = incrementBy;
	}

	@Column(name = "Counter_Length")
	public Integer getCounterLength() {
		return this.counterLength;
	}

	public void setCounterLength(Integer counterLength) {
		this.counterLength = counterLength;
	}

	@Column(name = "Current_Counter")
	public Integer getCurrentCounter() {
		return this.currentCounter;
	}

	public void setCurrentCounter(Integer currentCounter) {
		this.currentCounter = currentCounter;
	}

	@Column(name = "Owner_Id")
	public Integer getOwnerId() {
		return this.ownerId;
	}

	public void setOwnerId(Integer ownerId) {
		this.ownerId = ownerId;
	}

	@Column(name = "Created_By")
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Created_Date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "Last_Modified_By")
	public Integer getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(Integer lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Last_Modified_Date", length = 19)
	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	@Column(name = "Attribute_1", length = 20)
	public String getAttribute1() {
		return this.attribute1;
	}

	public void setAttribute1(String attribute1) {
		this.attribute1 = attribute1;
	}

	@Column(name = "Attribute_2", length = 20)
	public String getAttribute2() {
		return this.attribute2;
	}

	public void setAttribute2(String attribute2) {
		this.attribute2 = attribute2;
	}

	@Column(name = "Attribute_3", length = 20)
	public String getAttribute3() {
		return this.attribute3;
	}

	public void setAttribute3(String attribute3) {
		this.attribute3 = attribute3;
	}

}
