package com.embark.entity;

// Generated 18 Jul, 2016 10:32:30 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import com.google.gson.annotations.Expose;

/**
 * TallyInvoice generated by hbm2java
 */
@Entity
@Table(name = "tally_invoice", catalog = "salex", uniqueConstraints = @UniqueConstraint(columnNames = "EXTERNAL_VOUCHERKEY"))
public class TallyInvoice implements java.io.Serializable {

	@Expose private Integer id;
	@Expose private BigDecimal voucherKey;
	@Expose private String partyLedgerName;
	@Expose private String ledgerName;
	@Expose private String partyName;
	@Expose private BigDecimal externalVoucherkey;
	@Expose private String stockItemName;
	@Expose private Float rate;
	@Expose private BigDecimal billedQty;
	@Expose private Date createDate;
	@Expose private Date invoiceDate;
	@Expose private Date lastMdfDate;

	public TallyInvoice() {
	}

	public TallyInvoice(String ledgerName, BigDecimal externalVoucherkey) {
		this.ledgerName = ledgerName;
		this.externalVoucherkey = externalVoucherkey;
	}

	public TallyInvoice(BigDecimal voucherKey, String partyLedgerName,
			String ledgerName, String partyName, BigDecimal externalVoucherkey,
			String stockItemName, Float rate, BigDecimal billedQty,
			Date createDate, Date invoiceDate, Date lastMdfDate) {
		this.voucherKey = voucherKey;
		this.partyLedgerName = partyLedgerName;
		this.ledgerName = ledgerName;
		this.partyName = partyName;
		this.externalVoucherkey = externalVoucherkey;
		this.stockItemName = stockItemName;
		this.rate = rate;
		this.billedQty = billedQty;
		this.createDate = createDate;
		this.invoiceDate = invoiceDate;
		this.lastMdfDate = lastMdfDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "VOUCHER_KEY", precision = 30, scale = 0)
	public BigDecimal getVoucherKey() {
		return this.voucherKey;
	}

	public void setVoucherKey(BigDecimal voucherKey) {
		this.voucherKey = voucherKey;
	}

	@Column(name = "PARTY_LEDGER_NAME", length = 4500)
	public String getPartyLedgerName() {
		return this.partyLedgerName;
	}

	public void setPartyLedgerName(String partyLedgerName) {
		this.partyLedgerName = partyLedgerName;
	}

	@Column(name = "LEDGER_NAME", nullable = false, length = 4500)
	public String getLedgerName() {
		return this.ledgerName;
	}

	public void setLedgerName(String ledgerName) {
		this.ledgerName = ledgerName;
	}

	@Column(name = "PARTY_NAME", length = 4500)
	public String getPartyName() {
		return this.partyName;
	}

	public void setPartyName(String partyName) {
		this.partyName = partyName;
	}

	@Column(name = "EXTERNAL_VOUCHERKEY", unique = true, nullable = false, precision = 30, scale = 0)
	public BigDecimal getExternalVoucherkey() {
		return this.externalVoucherkey;
	}

	public void setExternalVoucherkey(BigDecimal externalVoucherkey) {
		this.externalVoucherkey = externalVoucherkey;
	}

	@Column(name = "STOCK_ITEM_NAME", length = 4500)
	public String getStockItemName() {
		return this.stockItemName;
	}

	public void setStockItemName(String stockItemName) {
		this.stockItemName = stockItemName;
	}

	@Column(name = "RATE", precision = 12, scale = 0)
	public Float getRate() {
		return this.rate;
	}

	public void setRate(Float rate) {
		this.rate = rate;
	}

	@Column(name = "BILLED_QTY", precision = 30, scale = 0)
	public BigDecimal getBilledQty() {
		return this.billedQty;
	}

	public void setBilledQty(BigDecimal billedQty) {
		this.billedQty = billedQty;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "INVOICE_DATE", length = 19)
	public Date getInvoiceDate() {
		return this.invoiceDate;
	}

	public void setInvoiceDate(Date invoiceDate) {
		this.invoiceDate = invoiceDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_MDF_DATE", length = 19)
	public Date getLastMdfDate() {
		return this.lastMdfDate;
	}

	public void setLastMdfDate(Date lastMdfDate) {
		this.lastMdfDate = lastMdfDate;
	}

}
